services:
  - type: web
    name: dbt-therapist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 dbt:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: dbt.py
    plan: free
